import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { stableId } from '../src/identity.ts'
import {
  encodeMuJSON,
  formatEncoderNumber,
  formatIso8601Date,
  formatSerializationNumber,
  sha256Hex,
} from '../src/hashing.ts'

// Byte-parity vectors generated by running scripts/gen-vectors.swift against
// the actual MuCore pure functions (Swift 6.3.3 on this machine).
interface Vector {
  name: string
  value: string
}

function loadVectors(): Map<string, string> {
  const raw = readFileSync(new URL('./fixtures/swift-vectors.txt', import.meta.url), 'utf8')
  const map = new Map<string, string>()
  for (const line of raw.split('\n')) {
    if (line === '') continue
    const tab = line.indexOf('\t')
    const name = line.slice(0, tab)
    // Reverse of the generator's emit(): \\(\\|n|") escapes, single pass,
    // so `\\` (escaped backslash) is consumed before `\n` / `\"`.
    const value = line.slice(tab + 1).replace(/\\(\\|n|")/g, (_m, ch: string) =>
      ch === '\\' ? '\\' : ch === 'n' ? '\n' : '"',
    )
    map.set(name, value)
  }
  return map
}

const V = loadVectors()

describe('sha256Hex matches Swift Data.muSHA256', () => {
  it('hashes a known string', () => {
    expect(sha256Hex('hello')).toBe(
      '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824',
    )
  })
})

describe('stableId matches MuStableIdentity.uuid', () => {
  it('derives the project stable ID', () => {
    expect(stableId('mu.project.repository', ['/Users/test/project'])).toBe(V.get('stable_project'))
  })

  it('derives the runtime actor stable ID', () => {
    expect(stableId('mu.actor.runtime', ['d9f4d3f2-1a2b-4c3d-8e5f-60718293a4b5'])).toBe(
      V.get('stable_actor_runtime'),
    )
  })

  it('derives the conflict stable ID with sorted record IDs', () => {
    expect(
      stableId('mu.context-conflict', [
        'a1b2c3d4-e5f6-4789-abcd-ef0123456789',
        'api.rate.limit',
        '01234567-89ab-4cde-8f01-23456789abcd',
        '9f8e7d6c-5b4a-4321-8f0e-dcba98765432',
      ]),
    ).toBe(V.get('stable_conflict'))
  })

  it('is deterministic and version-5-shaped', () => {
    const a = stableId('ns', ['x'])
    const b = stableId('ns', ['x'])
    expect(a).toBe(b)
    expect(a[14]).toBe('5')
  })
})

describe('formatIso8601Date matches Swift JSONEncoder .iso8601', () => {
  it('formats UTC with Z and no fractional seconds', () => {
    expect(formatIso8601Date(new Date(1_752_433_665_000))).toBe('2025-07-13T19:07:45Z')
  })

  it('truncates milliseconds like the Swift formatter', () => {
    expect(formatIso8601Date(new Date(1_752_433_665_123))).toBe('2025-07-13T19:07:45Z')
  })
})

describe('encodeMuJSON matches Swift JSONEncoder', () => {
  it('encodes dates byte-identically', () => {
    const encoded = encodeMuJSON({ date: new Date(1_752_433_665_000) })
    expect(sha256Hex(encoded)).toBe(V.get('date_sha256'))
    expect(encoded).toBe(V.get('date_json'))
  })

  it('encodes a record fingerprint material byte-identically', () => {
    const material = {
      schemaVersion: 1,
      canonicalizationVersion: 'mu-json-v1',
      projectID: 'a1b2c3d4-e5f6-4789-abcd-ef0123456789',
      sourceID: '9f8e7d6c-5b4a-4321-8f0e-dcba98765432',
      externalID: 'msg-42',
      kind: 'fact',
      subject: 'api.rate.limit',
      contentSHA256: 'deadbeef'.padEnd(64, '0'),
      scope: {
        environment: 'prod',
        taskID: '01234567-89ab-4cde-8f01-23456789abcd',
      },
      sensitivity: 'restricted',
      accessPolicyID: 'b4b4b4b4-b4b4-b4b4-b4b4-b4b4b4b4b4b4',
      confidence: 0.95,
      validFrom: new Date(1_752_433_665_000),
      validUntil: new Date(1_752_433_665_123),
      createdByActorID: 'd9f4d3f2-1a2b-4c3d-8e5f-60718293a4b5',
      createdAt: new Date(1_752_433_665_000),
    }
    const encoded = encodeMuJSON(material)
    expect(encoded).toBe(V.get('record_material_json'))
    expect(sha256Hex(encoded)).toBe(V.get('record_material_sha256'))
  })

  it('encodes a policy fingerprint material byte-identically', () => {
    const material = {
      schemaVersion: 1,
      projectID: 'a1b2c3d4-e5f6-4789-abcd-ef0123456789',
      subjectKind: 'record',
      subjectID: '9f8e7d6c-5b4a-4321-8f0e-dcba98765432',
      familyID: 'c1c2c3c4-c5c6-c7c8-c9ca-cbcccdcecfd0',
      version: 2,
      supersedesPolicyID: 'd1d2d3d4-d5d6-d7d8-d9da-dbdcdddedfd0',
      namespace: 'project/shared',
      sensitivity: 'project',
      visibility: 'task_participants',
      allowedActorIDs: [
        'a1b2c3d4-e5f6-4789-abcd-ef0123456789',
        '01234567-89ab-4cde-8f01-23456789abcd',
      ],
      allowedPrincipalIDs: [],
      allowedTaskIDs: ['e1e2e3e4-e5e6-e7e8-e9ea-ebecedeeef00'],
      createdByActorID: 'd9f4d3f2-1a2b-4c3d-8e5f-60718293a4b5',
      createdAt: new Date(1_752_433_665_000),
    }
    const encoded = encodeMuJSON(material)
    expect(encoded).toBe(V.get('policy_material_json'))
    expect(sha256Hex(encoded)).toBe(V.get('policy_material_sha256'))
  })

  it('escapes strings exactly like Swift', () => {
    const encoded = encodeMuJSON({
      slash: 'a/b/c',
      quote: 'say "hi"',
      backslash: 'path\\file',
      newline: 'line1\nline2',
      unicode: 'héllo 世界 🚀',
      nested: { x: [1, 2.5, null] },
    })
    expect(sha256Hex(encoded)).toBe(V.get('escape_sha256'))
    expect(encoded).toBe(V.get('escape_json'))
  })

  it('omits undefined keys like Swift encodeIfPresent', () => {
    expect(encodeMuJSON({ a: 1, b: undefined, c: { d: undefined, e: 2 } })).toBe(
      '{"a":1,"c":{"e":2}}',
    )
  })
})

describe('formatEncoderNumber matches Swift JSONEncoder number output', () => {
  const cases: Array<[number, string]> = [
    [0.1, '0.1'],
    [0.2, '0.2'],
    [1, '1'],
    [42, '42'],
    [1.5, '1.5'],
    [-0, '-0'],
    [0.3333333333333333, '0.3333333333333333'],
    [1e21, '1e+21'],
    [1e-7, '1e-07'],
    [1.5e-7, '1.5e-07'],
    [123456789.123456789, '123456789.12345679'],
    [1e6, '1000000'],
    [3.141592653589793, '3.141592653589793'],
  ]
  for (const [input, expected] of cases) {
    it(`formats ${input} as ${expected}`, () => {
      expect(formatEncoderNumber(input)).toBe(expected)
    })
  }

  it('rejects non-finite numbers', () => {
    expect(() => formatEncoderNumber(NaN)).toThrow()
    expect(() => formatEncoderNumber(Infinity)).toThrow()
  })
})

describe('formatSerializationNumber matches Swift JSONSerialization output', () => {
  const cases: Array<[number, string]> = [
    [0.1, '0.10000000000000001'],
    [0.2, '0.20000000000000001'],
    [1, '1'],
    [42, '42'],
    [1.5, '1.5'],
    [-0, '-0'],
    [0.3333333333333333, '0.33333333333333331'],
    [1e21, '1e+21'],
    [1e-7, '9.9999999999999995e-08'],
    [1.5e-7, '1.4999999999999999e-07'],
    [123456789.123456789, '123456789.12345679'],
    [1e6, '1000000'],
    [3.141592653589793, '3.1415926535897931'],
  ]
  for (const [input, expected] of cases) {
    it(`formats ${input} as ${expected}`, () => {
      expect(formatSerializationNumber(input)).toBe(expected)
    })
  }
})

describe('canonicalData path (JSONSerialization style)', () => {
  it('produces the canonical JSON vector for a nested value', () => {
    const value = {
      z_last: [1, 0.5, 'a/b', null, true],
      a_first: { nested: 'héllo', flag: false },
      num_negzero: 0,
      num_frac: 0.1,
      num_exp: 1e21,
      num_exp_small: 1e-7,
    }
    const encoded = encodeMuJSON(value, { serializationNumbers: true })
    expect(encoded).toBe(V.get('cv_json'))
    expect(sha256Hex(encoded)).toBe(V.get('cv_sha256'))
  })
})
